Import('TOOL_ROOT')

from building import *

cwd = GetCurrentDir()

src = Split("""
""")

if GetDepend(['CONFIG_REALTEK_BSP_TOUCH_816S_8762D_320']):
    src += ['touch_816s_8762d_320.c']

if GetDepend(['CONFIG_REALTEK_BSP_TOUCH_FT6336_8762D']):
    src += ['touch_ft6336_8762d.c']

if GetDepend(['CONFIG_REALTEK_BSP_TOUCH_CST816D']):
    src += ['touch_cst816d.c']

CPPPATH = [cwd]

group = DefineGroup('touch_driver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')