

from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")


if GetDepend(['CONFIG_REALTEK_ST77989_240_320']):
    src += ['lcd_st7789_240_spi.c']

CPPPATH = [cwd]

group = DefineGroup('lcd_low_driver', src, CPPPATH = CPPPATH, depend = ['CONFIG_REALTEK_8762E_DEVICE'])
# print(src)
# print(group)

Return('group')