from building import *


src   = Glob('*.c')
if GetDepend(['CONFIG_REALTEK_8762D_DEVICE']):
    SrcRemove(src,'syscall_mem.c')
group = []



group = DefineGroup('Compiler', src, depend = [''])



Return('group')
