Import('TOOL_ROOT')

from building import *

cwd = GetCurrentDir()

src = Split("""
""")


if GetDepend(['BSP_USING_TOUCH']):
    if GetDepend(['BSP_TOUCH_ZT2717']):
        src += ['touch_zt2717.c']
    if GetDepend(['BSP_TOUCH_GT911']):
        src += ['touch_gt911.c']
CPPPATH = [cwd]

group = DefineGroup('touch_driver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')