
from building import *

cwd = GetCurrentDir()

src = Split("""
""")


if GetDepend(['USING_8772F_DEVICE']) or GetDepend(['SOC_RTL_8772F']):
    group = []
    Return('group')

if GetDepend(['BSP_USING_DSI']):
    src += ['rtl_dsi.c']
if GetDepend(['BSP_USING_LCDC']) or GetDepend(['CONFIG_RTK_USING_LCDC_WEARABLE']):
    src += ['rtl_lcdc.c']
if GetDepend(['BSP_USING_DBIB']):
    src += ['rtl_lcdc_dbib.c']
if GetDepend(['BSP_USING_DBIC']):
    src += ['rtl_lcdc_dbic.c']
if GetDepend(['BSP_USING_EDPI']) or GetDepend(['BSP_USING_DSI']) or GetDepend (['CONFIG_RTK_USING_EDPI']):
    src += ['rtl_lcdc_edpi.c']
if GetDepend(['USING_8762G_DEVICE']):
    src += ['rtl_ppe.c']
    src += ['rtl_rtzip.c']
if GetDepend(['USING_8763EP_DEVICE']):
    #src += ['rtl_PPEV2.c']
    src += ['rtl_rtzip.c']

CPPPATH = [cwd]

group = DefineGroup('peripheral', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
