
from building import *

cwd = GetCurrentDir()

src = Split("""
""")


if GetDepend(['USING_8772F_DEVICE']):
    group = []
    Return('group')

if GetDepend(['BSP_USING_DSI']):
    src += ['rtl_dsi.c']
if GetDepend(['BSP_USING_LCDC']):
    src += ['rtl_lcdc.c']
    src += ['rtl_ppe.c']
    src += ['rtl_rtzip.c']
if GetDepend(['BSP_USING_DBIB']):
    src += ['rtl_lcdc_dbib.c']
if GetDepend(['BSP_USING_DBIC']):
    src += ['rtl_lcdc_dbic.c']
if GetDepend(['BSP_USING_EDPI']) or GetDepend(['BSP_USING_DSI']):
    src += ['rtl_lcdc_edpi.c']

CPPPATH = [cwd]

group = DefineGroup('peripheral', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
