# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
objs = []
list = os.listdir(cwd)
src = Split("""""")
CPPPATH = [cwd]
CPPDEFINES = ['DEFINE_RTK_BT_TODO']
if GetDepend(['RTL8772F']):
    Import('SDK_ROOT')
    src += [SDK_ROOT + '/bin/mdk/gap_utils.lib']
    src += [SDK_ROOT + '/bin/mdk/bt_mgr.lib']
    src += [SDK_ROOT + '/bin/mdk/console.lib']
    src += [SDK_ROOT + '/bin/mdk/audio.lib']
    src += [SDK_ROOT + '/bin/mdk/sysm.lib']
    src += [SDK_ROOT + '/bin/mdk/remote.lib']
    src += [SDK_ROOT + '/bin/mdk/hal_utils.lib']
if GetDepend(['USING_BR_TASK']) or GetDepend(['USING_BLE_TASK']):
    src += ['bt_task.c']
if GetDepend(['USING_BR_TASK']):
    src += ['app_bond.c']
    src += ['app_cfg.c']
    src += ['mcu_cfg.c']
    src += ['app_util.c']
    src += ['app_transfer.c']
    src += ['app_br_link_util.c']
    CPPDEFINES += ['RTK_BR_TASK']
if GetDepend(['MODULE_USING_DATABASE']) and GetDepend(['USING_BLE_TASK']):
    src += ['app_le_link_util.c']
if GetDepend(['USING_BLE_TASK']):
    CPPDEFINES += ['RTK_BLE_TASK']
    
group = DefineGroup('bt_app', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend(['USING_BR_TASK']) or GetDepend(['USING_BLE_TASK']):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
