#Import('rt_config')
from building import *

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
""")

src += ['romfs.c']

CPPPATH = [cwd]




group = DefineGroup('fs', src, depend = ['CONFIG_REALTEK_ROMFS'], CPPPATH = CPPPATH)

Return('group')