
from building import *


cwd     = GetCurrentDir()
objs = []
cwd     = GetCurrentDir()
src     = Glob('*.c')
CPPPATH = [cwd]
list = os.listdir(cwd)

CPPDEFINES = ['RTK_MODULE_USING_DATABASE']

group = DefineGroup('database', src, depend = ['CONFIG_REALTEK_MODULE_DATABASE'], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

if GetDepend('CONFIG_REALTEK_MODULE_DATABASE'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')
