Import('TOOL_ROOT')

from building import *

cwd = GetCurrentDir()

src = Split("""
""")
if GetDepend(['BSP_USING_GPIO']):
    if GetDepend(['BSP_USING_KEY_BUTTON']):
        src += ['key_button_8772f.c']

CPPPATH = [cwd]

group = DefineGroup('key_button', src, depend = ['USING_8772F_DEVICE'], CPPPATH = CPPPATH)

Return('group')