# RT-Thread building script for GuiEngine demo

from building import *

cwd = GetCurrentDir()
src = Split("""
""")

src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('fatfs', src, depend = ['MODULE_USING_FATFS'], CPPPATH = CPPPATH)

Return('group')
