Import('TOOL_ROOT')

from building import *

cwd = GetCurrentDir()
list = os.listdir(cwd)

# add the general drivers.
src = Split("""
""")

if GetDepend(['CONFIG_REALTEK_BR_TASK']):
    src += ['app_cmd.c']
    src += ['app_report.c']


CPPPATH = [cwd]

group = DefineGroup('bt_app', src, depend = [''], CPPPATH = CPPPATH)

Return('group')