# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
group = []
src   = Glob('*.c')
CPPPATH = [cwd]
list = os.listdir(cwd)

group = DefineGroup('tuya_ble_sdk', src, depend = ['CONFIG_REALTEK_TUYA_BLE_SDK'], CPPPATH = CPPPATH)

if GetDepend('CONFIG_REALTEK_TUYA_BLE_SDK'):
    for d in list:
        path = os.path.join(cwd, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            group = group + SConscript(os.path.join(d, 'SConscript'))


Return('group')
