Import('TOOL_ROOT')

Import('SDK_ROOT')
from building import *

cwd = GetCurrentDir()
list = os.listdir(cwd)

# add the general drivers.
src = Split("""
""")


if GetDepend(['DFU_BLE_SERVICE']):
    src += [SDK_ROOT + '/src/ble/profile/server/dfu_service.c']
if GetDepend(['USING_BR_TASK']):
    src += [SDK_ROOT + '/src/ble/profile/server/transmit_service.c']
if GetDepend(['PRIVATE_SERVICE']):
    src += ['wristband_private_service.c']
if GetDepend(['RTK_BLE_THROUGHPUT']):
    src += ['wristband_private_service.c']
if GetDepend(['CONFIG_RTK_USING_RTL87x2G_DEVICE']):
    src = []

CPPPATH = [cwd]

group = DefineGroup('realtek_ble', src, depend = [''], CPPPATH = CPPPATH)

Return('group')