# for module compiling
import os
from building import *

cwd  = GetCurrentDir()
group = []
src   = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('tuya_ble_sdk', src, depend = ['CONFIG_REALTEK_TUYA_BLE_SDK'], CPPPATH = CPPPATH)


Return('group')
